---
title: "Trabalho final"
---

**Objetivo:** Você deverá criar um documento com Quarto e compartilhar conoscoa. Esse trabalho final oferece orientações para que você pratique o que foi apresentado no curso.

**RECOMENDAÇÃO**: Faça as etapas sugeridas após cada aula.

**ATENÇÃO**: O recebimento do certificado está vinculado à entrega e aprovação deste trabalho final, além de ter frequência mínima de 75%.

<!-- ## Trabalhos entregues -->

<!-- Em breve! -->

```{r}
#| message: FALSE
#| echo: FALSE
# url <- "https://docs.google.com/spreadsheets/d/127pSSmT7o6zTjg9wslajkklXiXgb2lXAWwHcatZEYbU/"
# googlesheets4::gs4_auth(email = "milz.bea@gmail.com")
# sheet <- googlesheets4::read_sheet(url, "trabalhos-finais")
# 
# 
# sheet |>
#   dplyr::slice(-dplyr::n()) |> 
#   dplyr::arrange(Nome) |> 
#   dplyr::rename(url = Site, repo = GitHub, nome = Nome) |> 
#   dplyr::mutate(
#   url = dplyr::case_when(
#     !is.na(url) ~ glue::glue(
#       '<a href="{url}" target="_blank">{titulo}</a>'
#     ),
#     TRUE ~ ""
#   ),
#   repo_spec = stringr::str_remove(repo, "https://github.com/"),
#    repo = dplyr::case_when(
#     !is.na(repo) ~ glue::glue(
#       '<a href="{repo}" target="_blank">{repo_spec}</a>'
#     ),
#     TRUE ~ ""
#   )
#   
#   ) |> 
#   dplyr::select(nome, repo, url) |> 
#     reactable::reactable(searchable = TRUE, columns = list(
#         nome = reactable::colDef(html = TRUE, name = "Nome"),
#         url = reactable::colDef(html = TRUE, name = "Trabalho"),
#         repo = reactable::colDef(html = TRUE, name = "Repositório")),
#         defaultPageSize = 20
#     )
```

<!-- Obs:  Algumas pessoas realizaram o curso mas solicitaram que o trabalho final não fosse divulgado, e não constam na tabela acima. -->

## Etapas pré-codigo

-   Pense no tipo de relatório que quer criar, qual é o objetivo do mesmo e o público-alvo. 


- Exemplos:

    - Uma análise de dados da pesquisa, a ser apresentada para outras pessoas pesquisadoras.

    - Um tutorial com código em R ou Python.

    - Uma página pessoal de divulgação.
    
    - Um artigo científico (não precisa ser completo, pode ser a estrutura, mas é bom usar código para fazer as tabelas e gráficos).
    
    - Um dashboard.
    
    - Um livro (estrutura, primeiros capítulos, etc).


-   Escolha uma base de dados para utilizar! Segue algumas ideias:

    -   Alguma que você **tenha interesse**!

    -   Pacote [dados](https://cienciadedatos.github.io/dados/)

    -   Repositório [tidytuesday](https://github.com/rfordatascience/tidytuesday) (em inglês)

    -   Mais pacotes da comunidade BR: [mananciais](https://beatrizmilz.github.io/mananciais/), [reservatoriosBR](https://brunomioto.github.io/reservatoriosBR/), [qualR](https://quishqa.github.io/qualR/), [Outros](https://materiais-estudo-r.netlify.app/portugues.html#pacotes-da-comunidade)

    -   Alguma que você **tenha interesse**!

## Passo a passo com R

1)  Crie um Projeto do RStudio para realizar a tarefa. Lembre-se de boas práticas para nomear o projeto: não utilize espaços, caracteres especiais, acentuação. O seu projeto deverá chamar "trabalho_relatorios_nome_sobrenome" (tudo minúsculo, separado por `_`). Ex: `trabalho_relatorios_beatriz_milz`

**Todos os passos seguintes serão realizados neste projeto criado.**

2)  Crie a estrutura do seu projeto: uma pasta `dados`, onde adicionará bases de dados (se necessário), e uma pasta `img` para imagens (se necessário). Você pode criar manualmente, ou utilizando a função `fs::dir_create()`:

``` r
fs::dir_create("dados")
fs::dir_create("img")
```

3)  Crie o arquivo que será utilizado.

> File -\> New File -\> Quarto document.

Você deve salvar o arquivo com o nome `index.qmd`. Clique em `Render` assim que o arquivo for criado, e confira se o arquivo `index.html` foi gerado sem erros.

4)  Agora você pode usar sua criatividade e adicionar conteúdo ao relatório.

Isso depende do objetivo do relatório e o público-alvo.

Pense em quais opções de chunk utilizar em cada caso: você pretende mostrar o código ou escondê-lo? Faz sentido para o seu público alvo ler o seu código?

Adicione pelo menos:

-   Um parágrafo de texto, com marcações.

-   Um link para uma página da internet.

-   Uma imagem.

-   Uma tabela.

-   Caso saiba usar ggplot, tente adicionar um gráfico.

-   Caso seja uma análise de pesquisa, tente adicionar referências usando `.bib`.

## Conteúdos que podem ser úteis

- [Trabalhos finais feitos pela turma de 2023](https://beatrizmilz.github.io/2023-curso-de-verao-ime-usp-relatorios/trabalho_final.html)

- [Trabalhos finais feitos pela turma de 2022](https://beatrizmilz.github.io/2022-curso-de-verao-ime-usp-relatorios/trabalho_final.html)

- [Algumas dúvidas da turma de 2023](https://beatrizmilz.github.io/2023-curso-de-verao-ime-usp-relatorios/duvidas/)

- [Dicas para Relatórios](https://blog.curso-r.com/posts/2021-03-15-dicas-relatorios-r4ds1_relatorios/)

- [Dicas para Gráficos](https://blog.curso-r.com/posts/2020-17-02-dicas-relatorios-r4ds1_graficos/)

- [Dicas para formatar tabelas](https://blog.curso-r.com/posts/2020-12-03-dicas-relatorios-r4ds1_tabelas/)



<!-- inicio font awesome -->

```{=html}
<script src="https://kit.fontawesome.com/1f72d6921a.js" crossorigin="anonymous"></script>
```
<!-- final font awesome -->
